In [ ]:
df=[]
files=[]
import pandas as pd
import re

In [5]:
import datetime
req=datetime.date.today().strftime("%Y-%m-%d")
req

'2020-09-03'

In [8]:
import os 
directory=os.path.join("C://","Users/92335/car-analysis")
for root,dirs,files in os.walk(directory):
    for file in files:
        if file.endswith(".csv"):
            df.append(pd.read_csv(file,error_bad_lines=False))

b'Skipping line 4758: expected 18 fields, saw 19\nSkipping line 6447: expected 18 fields, saw 19\nSkipping line 11195: expected 18 fields, saw 19\nSkipping line 14231: expected 18 fields, saw 19\nSkipping line 16311: expected 18 fields, saw 19\nSkipping line 30007: expected 18 fields, saw 21\n'
b'Skipping line 47136: expected 18 fields, saw 19\nSkipping line 49056: expected 18 fields, saw 20\n'
b'Skipping line 67284: expected 18 fields, saw 19\n'
C:\Users\92335\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
b'Skipping line 7675: expected 19 fields, saw 20\nSkipping line 18065: expected 19 fields, saw 20\nSkipping line 18734: expected 19 fields, saw 20\nSkipping line 21341: expected 19 fields, saw 20\n'
b'Skipping line 47314: expected 19 fields, saw 20\nSkipping line 48803: expected 19 fields, saw 21\n'
b'Skipping line 4328: expected 19 fields, saw 20\nSkipping line 10330: expected 19 fields, saw 20\nSkipping line 17583: expected 19 fields, saw 20\n'
b'Skipping line 39861: expected 19 fields, saw 21\n'
b'Skipping line 2170: expected 19 fields, saw 20\nSkipping line 2768: expected 19 fields, saw 21\nSkipping line 15471: expected 19 fields, saw 20\nSkipping line 21238: expected 19 fields, saw 20\n'

In [10]:
l=len(df)
for i in range(l):
    df[i]=df[i][["Make","Model","Year","Views","Days Online"]]

In [17]:
clean_df=[i for i in range(l)]
for i in range(l):
    clean_df[i]=df[i].dropna()

In [18]:
import re
for i in range(l):
    
    for index,row in clean_df[i].iterrows():
        
        row["Days Online"]=row["Days Online"].strip()
        if row["Days Online"][-4:]=="hour" or row["Days Online"][-5:]=="hours":
            num=eval(re.sub('[^0-9]','', row["Days Online"]))/24
            row["Days Online"]=num
        elif row["Days Online"][-4:]=="mins" or row["Days Online"][-3:]=="min":
            num=eval(re.sub('[^0-9]','', row["Days Online"]))/(60*24)
            row["Days Online"]= num
        elif row["Days Online"][-3:]=="day" or row["Days Online"][-4:]=="days":
            num=eval(re.sub('[^0-9]','', row["Days Online"]))
            row["Days Online"]= num
    
            
        
        row["Views"]=row["Views"].replace(r',','')
        row["Views"]=eval(row["Views"])

In [20]:
aggregate_functions={"Views":'sum','Days Online':'sum'}
for i in range(l):
    clean_df[i]=clean_df[i].groupby(["Model","Make","Year"]).aggregate(aggregate_functions)

In [22]:
for i in range(l):
    for index,row in clean_df[i].iterrows():
        if row['Days Online']<1:
            row['Days Online']=1

In [26]:
for i in range(l):
    clean_df[i]['Views Per Day']=clean_df[i]["Views"]/clean_df[i]['Days Online']
    clean_df[i]["Views Per Day"]=clean_df[i]["Views Per Day"].astype(float)
    clean_df[i]=clean_df[i].sort_values(by=["Views"],ascending=False)

In [41]:
final_df=clean_df[0]
for i in range(1,l):
    clean_df[i]=clean_df[i].rename(columns={'Views Per Day':'Views Per Day {}'.format(i)})
clean_df[3]

                                Views  Days Online  Views Per Day 3
Model       Make          Year
Golf        Volkswagen    2015  84087  4133.916667        20.340758
                          2013  70736  2843.083333        24.880030
                          2010  69730  2137.083333        32.628583
                          2011  64826  2271.333333        28.540945
                          2008  64181  2448.944444        26.207618
5-Series    BMW           2011  56612  2156.500000        26.251797
Golf        Volkswagen    2016  53297  3353.166667        15.894528
                          2012  51646  2165.708333        23.847163
                          2014  49280  2252.250000        21.880342
3-Series    BMW           2007  49154  2245.916667        21.885941
Focus       Ford          2017  49008  4952.588889         9.895431
5-Series    BMW           2017  48407  3251.250000        14.888735
Golf        Volkswagen    2017  48299  3812.166667        12.669698
Passat      Volkswagen    2016  48189  2285.456250        21.085068
3-Series    BMW           2010  47675  1556.416667        30.631258
A6          Audi          2013  47523  1571.208333        30.246148
Focus       Ford          2009  47378  2037.416667        23.253957
5-Series    BMW           2008  47278  1535.750000        30.784958
Focus       Ford          2008  47166  2419.833333        19.491425
Passat      Volkswagen    2008  47100  1696.208333        27.767815
3-Series    BMW           2008  46283  1265.625000        36.569284
                          2013  46025  1445.500000        31.840194
A4          Audi          2011  45634  1441.958333        31.647239
Focus       Ford          2015  44878  3208.083333        13.989038
A4          Audi          2009  44741  1319.333333        33.911824
Passat      Volkswagen    2011  43585  1837.041667        23.725646
Golf        Volkswagen    2005  43079  1518.875000        28.362439
E-Class     Mercedes-Benz 2014  43036  1477.541667        29.126759
Focus       Ford          2016  42526  3174.583333        13.395774
3-Series    BMW           2012  41714  1037.750000        40.196579
...                               ...          ...              ...
NV400       Nissan        2020     22     0.833333        26.400000
3000 Series Foden         2002     22     1.000000        22.000000
Mii         SEAT          2013     22     2.000000        11.000000
PRIUS+      Toyota        2012     21     0.791667        26.526316
123         Mercedes-Benz 2016     21     4.000000         5.250000
Vito        Mercedes-Benz 2015     21     0.416667        50.400000
108         Peugeot       2018     20     0.750000        26.666667
Ka          Ford          2014     20     0.583333        34.285714
ECOSPORT    Ford          2017     19     3.000000         6.333333
Ix20        Hyundai       2014     19     0.958333        19.826087
Corsa-E     Opel          2020     18     2.000000         9.000000
C3          Citroen       2019     16     0.833333        19.200000
Mondeo      Ford          2000     16     0.750000        21.333333
Meriva      Vauxhall      2015     16     0.916667        17.454545
D-Max       Isuzu         2002     16     0.500000        32.000000
XE          Peugeot       2015     15     0.916667        16.363636
Fox         Volkswagen    2011     15     0.041667       360.000000
S60         Volvo         2007     15     0.750000        20.000000
Dacia       Dacia         2017     15     0.583333        25.714286
Nemo        Citroen       2014     14     0.041667       336.000000
Beetle      Volkswagen    2015     13     0.024306       534.857143
Espace      Renault       2011     12     1.000000        12.000000
Touareg     Volkswagen    2012     12     0.083333       144.000000
Myvi        Perodua       2013     11     0.027083       406.153846
Master      Renault       2020     10     1.000000        10.000000
HiAce       Toyota        2018      9     0.250000        36.000000
A1          Opel          2008      9     0.750000        12.000000
Scenic      Renault       2020      7     0.875000         8.000000
Dispatch    Citroen       2019      6     0.833333         7.200000
E220        Mercedes-Benz 2019      3     0.002083      1440.000000

[5127 rows x 3 columns]

In [42]:
for i in range(1,3):
    final_df=pd.concat(clean_df[i])

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"